[connections.snowflake]
account = "GTKKEQF-YQB97213"
user = "ADITIVAIDYA"
password = "Panda@boka1009"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
